"""refactor booking status

Revision ID: c1f53b117fcc
Revises: a1b2c3d4e5f6
Create Date: 2026-07-12 16:47:26.418076
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1f53b117fcc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', postgresql.ENUM('Upcoming', 'Ongoing', 'Completed', 'Cancelled', name='booking_status_enum'), server_default=sa.text("'Upcoming'::booking_status_enum"), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'is_cancelled')
    # ### end Alembic commands ###
