"""Add scheduled job tracking markers

Revision ID: cfbd70859346
Revises: 0001_initial_schema
Create Date: 2026-07-12 15:55:26.804974
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfbd70859346'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('upload_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('allocations', sa.Column('overdue_alert_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset_categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('assets_asset_tag_key'), 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.add_column('bookings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('employees_email_key'), 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.add_column('maintenance_requests', sa.Column('overdue_alert_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_requests', 'overdue_alert_sent_at')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('bookings', 'reminder_sent_at')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=False)
    op.create_unique_constraint(op.f('assets_asset_tag_key'), 'assets', ['asset_tag'], postgresql_nulls_not_distinct=False)
    op.drop_column('asset_categories', 'is_active')
    op.drop_column('allocations', 'overdue_alert_sent_at')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
